version: "3.9"

services:
    db:
        container_name: laravel-react-template-db
        image: postgres:16.1-alpine
        ports:
            - "32754:5432"
        env_file:
            - .env
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
        volumes:
            - ./data:/var/lib/postgresql/data

    app:
        container_name: laravel-react-template-app
        image: php:8.3-apache
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - laravel-react-template:/var/www/larve-react-template

volumes:
    laravel-react-template:
